// mfe-dashboard/src/pages/OverviewPage.tsx
import { useEffect } from "react";
import { store } from "shared/store";
import styles from "../index.module.css";

export default function OverviewPage() {
  useEffect(() => {
    console.log("shared/store __id in mfe-dashboard:", store.__id);
  }, []);

  return (
    <div className={styles.card}>
      <h1>Overview</h1>
      <p>Summary widgets would go here.</p>
    </div>
  );
}

// mfe-settings/src/pages/OverviewPage.vue
<script setup lang="ts">
import { onMounted } from "vue";
import { store } from "shared/store";

onMounted(() => {
  console.log("shared/store __id in mfe-settings:", store.__id);
});
</script>

<template>
  <div class="card">
    <h1>Settings Overview</h1>
    <p>Account preferences and configuration would go here.</p>
  </div>
</template>
